# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_name', models.CharField(max_length=200)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=250)),
                ('introduction', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('hero_image_alt', models.TextField(blank=True, default='')),
                ('hero_image_caption', models.TextField(blank=True, default='')),
                ('audio_transcript', models.TextField(blank=True, default='')),
                ('source_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'content_revisions',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=80)),
                ('native_name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='RevisionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('alt_text', models.TextField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'revision_images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('internal_name', models.CharField(max_length=200)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='StopTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stop_translations',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes requested'), ('revoked', 'Revoked')], max_length=20)),
                ('reviewer_name', models.CharField(max_length=200)),
                ('evidence_reference', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_records',
                'get_latest_by': ['recorded_at', 'id'],
            },
        ),
    ]
