# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('media', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='audio_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_revisions', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='based_on_source_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_revisions', to='content.contentrevision'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_content_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='hero_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_revisions', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_revisions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='content_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to='content.contentrevision'),
        ),
        migrations.AddField(
            model_name='revisionimage',
            name='content_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='content.contentrevision'),
        ),
        migrations.AddField(
            model_name='revisionimage',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_images', to='media.mediaasset'),
        ),
        migrations.AddField(
            model_name='revisionimage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_images', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stop',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='content.collection'),
        ),
        migrations.AddField(
            model_name='stop',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stop',
            name='source_language',
            field=models.ForeignKey(db_column='source_language_code', on_delete=django.db.models.deletion.PROTECT, related_name='source_for_stops', to='content.language'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='content.stop'),
        ),
        migrations.AddField(
            model_name='stoptranslation',
            name='language',
            field=models.ForeignKey(db_column='language_code', on_delete=django.db.models.deletion.PROTECT, related_name='stop_translations', to='content.language'),
        ),
        migrations.AddField(
            model_name='stoptranslation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_translations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='stoptranslation',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_stop_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stoptranslation',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_for_translations', to='content.contentrevision'),
        ),
        migrations.AddField(
            model_name='stoptranslation',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='content.stop'),
        ),
        migrations.AddField(
            model_name='stoptranslation',
            name='working_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='working_for_translations', to='content.contentrevision'),
        ),
        migrations.AddField(
            model_name='contentrevision',
            name='stop_translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='content.stoptranslation'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['organization', 'archived_at'], name='collection_org_archive_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='collection_id_org_uq'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['content_revision', 'recorded_at', 'id'], name='approval_revision_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='revisionimage',
            constraint=models.UniqueConstraint(fields=('content_revision', 'position'), name='revision_image_position_uq'),
        ),
        migrations.AddConstraint(
            model_name='revisionimage',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='revision_image_position_ck'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['organization', 'collection'], name='stop_org_collection_idx'),
        ),
        migrations.AddConstraint(
            model_name='stoptranslation',
            constraint=models.UniqueConstraint(fields=('stop', 'language'), name='stop_language_uq'),
        ),
        migrations.AddConstraint(
            model_name='stoptranslation',
            constraint=models.UniqueConstraint(fields=('id', 'stop', 'organization'), name='translation_id_stop_org_uq'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('stop_translation', 'revision_number'), name='revision_translation_num_uq'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('id', 'stop_translation', 'stop', 'organization'), name='revision_identity_scope_uq'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('id', 'stop', 'organization'), name='revision_id_stop_org_uq'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='revision_id_org_uq'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gt', 0)), name='revision_number_ck'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.CheckConstraint(condition=models.Q(('based_on_source_revision__isnull', True), models.Q(('based_on_source_revision', models.F('id')), _negated=True), _connector='OR'), name='revision_source_not_self_ck'),
        ),
    ]
