# Generated by Django 5.2.17 on 2026-09-20 10:42

import apps.markers.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.markers.models.generate_marker_token, editable=False, max_length=32, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('placement_notes', models.TextField(blank=True, default='')),
                ('has_qr', models.BooleanField(default=True)),
                ('has_nfc', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('retirement_reason', models.TextField(blank=True, default='')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markers', to='content.stop')),
            ],
            options={
                'db_table': 'markers',
            },
        ),
        migrations.CreateModel(
            name='MarkerCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('not_tested', 'Not tested'), ('not_present', 'Not present')], default='not_tested', max_length=12)),
                ('nfc_result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('not_tested', 'Not tested'), ('not_present', 'Not present')], default='not_tested', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marker_checks', to=settings.AUTH_USER_MODEL)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='markers.marker')),
            ],
            options={
                'db_table': 'marker_checks',
                'get_latest_by': ['checked_at', 'id'],
            },
        ),
    ]
