# Generated by Django 5.2.17 on 2026-09-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'occurred_at'], name='audit_org_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'entity_type', 'entity_id'], name='audit_org_entity_idx'),
        ),
    ]
